import React from "react";
import Head from "next/head";
import Title from "../components/Title";
import styles from "../styles/Apps.module.css";
import { apps } from "../apps";
import AppCard from "../components/AppCard";

function Apps() {
  return (
    <>
      <Head>
        <title>Fran Studios | All Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ marginTop: "5rem" }}>
        <Title title="All Apps" />
        <section className={styles.appsContainer}>
          {apps.map((app) => (
            <AppCard
              name={app.name}
              preview={app.preview}
              icon={app.icon}
              key={app.id}
              app={app.app}
            />
          ))}
        </section>
      </main>
    </>
  );
}

export default Apps;
