import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import PrimaryBtnLink from "../components/PrimaryBtnLink";
import { colors } from "../constants/colors";
import NavLink from "../components/NavLink";
import LogoLink from "../components/LogoLink";
import Title from "../components/Title";
import AppCard from "../components/AppCard";
import { apps } from "../apps";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.presentationContainer}>
          <div className={styles.presentationInfoContainer}>
            <h5 style={{ color: colors.LIGHT_ORANGE }}>Mobile development</h5>
            <h1 className={styles.h1}>Work that we produce for our clients</h1>
            <p className={styles.infoDescription}>
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industrys standard.
            </p>
            <PrimaryBtnLink
              title="See all apps"
              bgColor={colors.LIGHT_ORANGE}
              borderRadius={9999}
            />
          </div>
          <div className={styles.presentationImgContainer}>
            <Image
              src="/presentation.png"
              width={280}
              height={500}
              alt="presentation"
            />
          </div>
        </section>
        <section className={styles.trendingAppsContainer}>
          <div className={styles.trendingTitleContainer}>
            <Title title="Currently Trending Apps" />
            <PrimaryBtnLink
              title="SEE ALL"
              borderRadius={5}
              bgColor="rgba(255,255,255,0.11)"
            />
          </div>
          <div className={styles.trendingAppsCardContainer}>
            {apps
              .filter((app) => app.trending)
              .map((app) => (
                <AppCard
                  name={app.name}
                  preview={app.preview}
                  icon={app.icon}
                  key={app.id}
                />
              ))}
          </div>
        </section>
        <section className={styles.relleno}></section>
      </main>

      <footer className={styles.footer}></footer>
    </>
  );
}
